USE ShopEase_DB;


-- SECTION C: AGGREGATION & DATA SUMMARIZATION


-- Q13: Count global transactions processed
SELECT COUNT(*) AS total_orders FROM orders;

-- Q14: Realized revenue generated by finalized transactions
SELECT SUM(total_amount) AS total_revenue FROM orders WHERE status = 'Delivered';

-- Q15: Calculate average value points grouped by category
SELECT category, AVG(unit_price) AS avg_price FROM products GROUP BY category;

-- Q16: Funnel volumetric status layout sorted by financial weight
SELECT status, COUNT(*) AS order_count, SUM(total_amount) AS revenue 
FROM orders GROUP BY status ORDER BY revenue DESC;

-- Q17: Minimum and Maximum product tier evaluations per division
SELECT category, MAX(unit_price) AS max_price, MIN(unit_price) AS min_price FROM products GROUP BY category;

-- Q18: Identify core high-end divisions using HAVING thresholds
SELECT category, AVG(unit_price) AS avg_price FROM products GROUP BY category HAVING AVG(unit_price) > 2000;


-- SECTION D: JOINS & RELATIONSHIPS


-- Q19: Identity lookup join mapping records to transaction items
SELECT o.order_id, o.order_date, c.first_name, c.last_name, o.total_amount 
FROM orders o 
INNER JOIN customers c ON o.customer_id = c.customer_id;

-- Q20: Comprehensive mapping showing all client data regardless of order histories
SELECT c.customer_id, c.first_name, c.last_name, o.order_id, o.status 
FROM customers c 
LEFT JOIN orders o ON c.customer_id = o.customer_id;

-- Q21: Multi-stage relational map connecting orders to underlying product items
SELECT oi.order_id, p.product_name, oi.quantity, oi.unit_price, oi.discount_pct 
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id
INNER JOIN products p ON oi.product_id = p.product_id;